data:
  path: /work/frink/mcinerney.de/datasets/mimic-iii/physionet.org/files/mimiciii/1.4/preprocessed
  dataset: reports_and_codes3
  cache_path: /work/frink/mcinerney.de/ehr-diagnosis-env-interface/.cache/cache-1
