data:
  path: /PHShome/dzm44/data/Dataset_8-1-2023/preprocessed
  dataset: bwh_er_data
  max_reports_considered: null
models:
  llm_evidence: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/outputs/wandb/offline-run-20240216_141857-tfvhvc4e/files/ckpt_epoch=110_updates=880.pt
  # llm_evidence: /scratch/mcinerney.de/ehr-diagnosis-agent-output/wandb/run-20230927_194029-jhtf7taf/files/ckpt_epoch=95_updates=679.pt
  # all_sentences: /scratch/mcinerney.de/ehr-diagnosis-agent-output/wandb/run-20230925_104538-57jsyt8v/files/ckpt_epoch=145_updates=1160.pt
model_outputs: {}
  # val1:
  #   interpretable: /scratch/mcinerney.de/ehr-diagnosis-agent-output/wandb/run-20230906_001007-uve48lpv/files/val_metrics_ckpt_epoch=180_updates=1440_episodes.csv
  #   interpretable_with_dropout: /scratch/mcinerney.de/ehr-diagnosis-agent-output/wandb/run-20230906_001046-9ha9a8jj/files/val_metrics_ckpt_epoch=330_updates=2640_episodes.csv
# static_bias_params: # for inference
#   - [-2.642675509576076]
#   - [-1.9572920156106348]
#   - [-1.5961686236710402]
static_bias_params: null
annotations:
  path: /PHShome/dzm44/code/ehr-diagnosis-env-interface/annotations
  target_anns_path: /PHShome/dzm44/code/ehr-diagnosis-env-interface/target_annotations
  hallucination_anns_path: /PHShome/dzm44/code/ehr-diagnosis-env-interface/hallucination_annotations
  model_explorer_anns_path: /PHShome/dzm44/code/ehr-diagnosis-env-interface/model_explorer_annotations
  complementary: []
  target_anns_complementary: []
  hallucination_anns_complementary: []
  model_explorer_anns_complementary: []
  hallucination_evidence_paths: []
  balance_samples: false
skip_query: true
query_type: zeros
ratio_negative_to_positive: .5
max_observed_reports: 20
env:
  # env_type: EHRDiagnosisEnv-v0
  env_type: FlanEHRDiagnosisEnv-v0
  # env_type: MistralEHRDiagnosisEnv-v0
  # llm_name: 'google/flan-t5-xxl'
  llm_name: '/PHShome/dzm44/models/flan-t5-xxl'
  # llm_name: 'mistralai/Mistral-7B-Instruct-v0.2'
  # llm_name: '/PHShome/dzm44/models/models--mistralai--Mistral-7B-Instruct-v0.2'
  # fmm_name: 'all-MiniLM-L6-v2'
  fmm_name: '/PHShome/dzm44/models/all-MiniLM-L6-v2'
  train_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_train_cache_flan_2
  val1_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val1_cache_flan_2
  val2_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val2_cache_flan_2
  test_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_test_cache_flan_2
  # train_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_train_cache_mistral_2
  # val1_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val1_cache_mistral_2
  # val2_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_val2_cache_mistral_2
  # test_cache_path: /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_test_cache_mistral_2
  reward_type: 'continuous_independent'
  other_args:
    top_k_evidence: 3
    num_future_diagnoses_threshold: 0
    match_confident_diagnoses: false
    match_potential_diagnoses: false
    true_positive_minimum: 0
    add_risk_factor_queries: false
    limit_options_with_llm: true
    use_confident_diagnosis_mapping: false
    stop_after_first_target: false
    skip_instances_with_gt_n_reports: 200
    add_diagnosis_options_from_caches:
      - /PHShome/dzm44/code/ehr-diagnosis-agent/ehr_diagnosis_agent/.cache/env_train_cache_flan_2
    added_diagnosis_options_threshold: 10
    limit_evidence_updates_to_k_reports: 1
