data:
  path: /work/frink/mcinerney.de/datasets/mimic-iii/physionet.org/files/mimiciii/1.4/preprocessed
  dataset: reports_and_codes3
  train_cache_path: /work/frink/mcinerney.de/ehr-diagnosis-env-interface/.cache/cache-train-1
  val_cache_path: /work/frink/mcinerney.de/ehr-diagnosis-env-interface/.cache/cache-val-1
  test_cache_path: /work/frink/mcinerney.de/ehr-diagnosis-env-interface/.cache/cache-test-1
